# -*- coding: utf-8 -*-
"""Copy of game.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14k7-ZOpcVcCU7f91zC5A_y8DZB-VRTX8
"""

import random
while True:
    choice=input('roll the dice? (y/n):').lower()
    if choice == 'y':
        die1=random.randint(1,6)
        die2=random.randint(1,6)
        print(f'({die1},{die2})')
    elif choice =='n':
        print('thanks for playing!')
        break
    else:
        print('invalid choice!')